
default_platform(:android)

platform :android do
  desc "Lane for android firebase app distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
      app: "1:116410668628:android:f63111bd0b8e19a7c9bfc1",
      firebase_cli_token:"1//03RShVJ42PlHNCgYIARAAGAMSNwF-L9IrO1PTF5ilI0oT_J70vrlI-aICsoW3GlsWDg6RPd0UjEi4TqhbrDHp-8c_pmnuwGyZ0bw",
      testers: "osamarizk262@gmail.com",
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk",
      
      
      release_notes:"fristmfastline firebase distribution"
      )
  end


end
